CREATE USER super1 SUPERUSER;

CREATE USER user1 CREATEDB CREATEROLE NOLOGIN REPLICATION BYPASSRLS PASSWORD 'pass';

CREATE ROLE role1 IN ROLE pg_moniter;

GRANT pg_moniter TO user1;
REVOKE pg_moniter FROM user1;

DROP ROLE role1;

DROP USER user1;
