version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-buildkit
    environment:
      ROLLBAR_ACCESS_TOKEN: 9be13c6e320a4034ad5f82e361315393
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - myrailsapp_bundle:/app/vendor/bundle
      - myrailsapp_node_modules:/app/node_modules

  nginx:
    image: nginx:1.17
    ports:
      - "8080:80"
    command: [nginx]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - myrailsapp_public:/app/public
      - myrailsapp_socket:/app/sockets

volumes:
  myrailsapp_bundle:
    driver: local
  myrailsapp_node_modules:
    driver: local
  myrailsapp_public:
    driver: local
  myrailsapp_socket:
    driver: local
