SET default_transaction_isolation TO "READ UNCOMMITTED";

BEGIN;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
COMMIT;

SET default_transaction_isolation TO "REPEATABLE READ";

START TRANSACTION ISOLATION LEVEL SERIALIZABLE;
COMMIT;
